.gitmodules
set up git submodule with https instead of ssh for consistency with terraform module repos
=> ci: set up git submodule with https instead of ssh

.gitignore, testhelper/test_options.go
Some modules such as the landing-zone module do not require a resource group to be passed as input. This change in the wrapper make it conditional.
=> fix: Make passing of resource group conditional

testhelper/tests.go
It was discovered during automated pipeline tests that the `RunTestUpgrade()` function was not switching back to the PR branch to do the final `terraform plan` step, and would instead stay on the master/main branch, which makes the test invalid.
This PR contains two fixes for this scenario:
1. Will use the original branch commit HASH, instead of the original branch name, to make absolutely sure that the final `git checkout` will point to the original code before running the final `plan` step of the upgrade test.
2. Remove the `git fetch` of "refs/heads/HEAD" as this was causing a local branch named "HEAD" and causing a warning in git operations inside the upgrade test due to ambiguous references to HEAD. Testing has shown that this additional fetch was not needed for this function.
Using …
=> fix: use git hash for upgrade test checkouts

testhelper/tests.go
Changed InitAndApply() to Apply() for the optional last step of Upgrade test, fixes kubecontrol missing issues after branch checkout.
Removing the `init` step of the final optional apply task of the upgrade test, which was removing any kube files generated by the previous `plan` step resulting in error (missing kubeconfig).
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
=> fix: remove init for optional upgrade step

README.md
Updates to [PR 357](https://github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper/pull/357). @toddgiguere, ping me if you want to discuss any changes.
- Updated the badges and contributing section to match the module template.
I assume this module is enabled for Renovate.
- Removed the now redundant `contributing` section near the top.
- Removed the `publishing` section, which isn't included with other modules
- Removed the heading called `Usage` and replaced with `Examples` and more specific headings.
This module is not a standard terraform project, so I don't think it needs a usage section.
- Changes to be consistent with the [public docs](https://github.com/terraform-ibm-modules/documentation/pull/28).
- Changes to fit IBM style and word usage.
---
- Merge by using "Squash and …
=> docs: editorial updates

common/general.go, testschematic/mock_test.go, testschematic/schematics.go, testschematic/schematics_test.go, testschematic/test_options.go, testschematic/tests.go, testschematic/tests_test.go
Fixes for several issues relating to recently added IBM Cloud Schematics test framework.
- Fix TAR file creation, do not use `os.Chdir()` which is not thread-safe
- Add retry mechanic to all Schematics SDK calls
- Logging of Schematic Workspace name in errors and test fail assertions
Bug fixes and minor enhancements
Fixes for several issues relating to recently added IBM Cloud Schematics test framework.
- Fix TAR file creation, do not use `os.Chdir()` which is not thread-safe
- Add retry mechanic to all Schematics SDK calls
- Logging of Schematic Workspace name in errors and test fail assertions
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the …
=> fix: issues with schematics api calls and tar creation

.secrets.baseline, testhelper/tests.go
It can be hard to see the reason why a resource has been changed when the consistency test fails. The Terraform CLI renders this nicely but because we are running plan with struct so we can ignore certain changes we loose the formatted output. I investigated implementing the code from the Terraform CLI to render for humans however it was too complex. Instead, if there is a valid change I re-run the plan but in the basic mode that uses the CLI output.
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) …
=> feat: output human-readable change log

common/general.go, common/general_test.go
Added new public function under `common` package to generate a new RSA keypair, and return the Public Key in OpenSSH Authorized Key format.
This new function can be used to generate throw-away public keys for use in test inputs.
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
Added new function: `common.GenerateSshRsaPublicKey`
This function will generate a new RSA public key and return it in OpenSSH format. Can be used to generate throw-away (but valid) public keys in test inputs.
Run the CI pipeline when the PR is …
=> feat: add common function to generate test SSH Public Key

.secrets.baseline, testhelper/tests.go
Adding extra logging for validation in pipeline
```
/run pipeline
```
=> fix: add logging

go.mod, go.sum, renovate.json
lock into vpc-go-sdk v0.41.0 and create renovate rule to prevent it from updating (see https://github.com/IBM/vpc-go-sdk/issues/49)
```
/run pipeline
```
=> fix: lock into vpc-go-sdk v0.41.0

testhelper/tests.go
fixes bug where pr directory is getting set too late 
```
/run pipeline
```
=> fix: bug setting the pr dir

.secrets.baseline, cloudinfo/cbr.go, cloudinfo/cbr_test.go, cloudinfo/mock_test.go, cloudinfo/service.go, testhelper/test_options.go, testhelper/tests.go
Adds a function for setting CBR Enforcment mode and a new Terraform option to automatically disable CBR rules in teardown before destroy.  
```
/run pipeline
```
=> add cbr cleanup

.secrets.baseline, go.mod, testschematic/schematics.go
Configuration for the `__netrc__` environment variable for schematics has changed from a json map to a simple json string containing an array of strings, in order of host/user/password.
Changed the implementation of `testschematic.addNetrcToWorkspaceEnv()` so that the appropriate format for netrc is sent to API.
Format reference here: https://cloud.ibm.com/docs/schematics?topic=schematics-download-modules-pvt-git
Changed the implementation of `testschematic.addNetrcToWorkspaceEnv()` so that the format of the `__netrc__` value in the schematics template environment variable is in the correct format.
The old format was a map of keys and strings, the new format is a simple array of strings with no keys.
Format reference here: https://cloud.ibm.com/docs/schematics?topic=schematics-download-mod …
=> fix: change schematic netrc from map to string array

.secrets.baseline, testhelper/tests.go
Add option to unskip unit tests. This will be an option after skipping unit tests, but you cannot disable upgrade tests once again after undoing a skip. Maybe we want to parse logs and json and look at commit message dates etc to do this logic https://maori.geek.nz/git-log-as-json-in-go-59d8e1d09fb5. 
```
/run pipeline
```
- Include information that users need to know about the …
=> feat: unskip tests

.secrets.baseline, cloudinfo/mock_test.go, cloudinfo/policy.go, cloudinfo/policy_test.go, cloudinfo/service.go, cloudinfo/service_test.go
Adding function to delete IAM policies
- `cloudinfo.DeleteIamPolicyByID` added
```
/run pipeline
```
=> iam policy management

.secrets.baseline, README.md, testhelper/terraform.go, testhelper/test_options.go, testhelper/tests.go, testhelper/tests_test.go
Add support to enable OpenTofu usage in tests. 
- add support to enable OpenTofu in testOptions
```
/run pipeline
```
=> Opentofu support

testprojects/tests.go, testprojects/tests_test.go
Simplified the TearDown logic in the testprojects package, more specifically around when TearDown is skipped for both resources and the parent stack project.
Added two new private functions in testprojects to wrap the logic around when both resource and project undeployment should take place to easier manage the logic in the future. Also added some new unit tests for these two functions to test all the various permutations and outcomes.
Simplified the logic around when resources or projects should get deleted during TestTearDown in the testprojects package, also added unit tests to verify all permutations.
Run the CI pipeline when the PR is ready for review …
=> feat: simplify testprojects TearDown logic

testhelper/test_options.go, testprojects/test_options.go, testprojects/tests.go
=> Increase default stack poll time to 60sec and expose as option

.secrets.baseline, testhelper/test_options.go, testhelper/tests.go
Ability to set API_DATA_IS_SENSITIVE to false so that if terraform detects some output value to be sensitive we can avoid the test failure.
```
/run pipeline
```
=> feat: ability to set value of API_DATA_IS_SENSITIVE to false

.secrets.baseline, common/git.go, testhelper/tests.go, testschematic/schematics.go, testschematic/test_options.go, testschematic/tests.go
This fix will revert the use of HTTPS configuration of schematics workspaces, and allow only TAR file upload to schematics for regular and upgrade tests. This change is to avoid a situation where schematics cannot properly determine or use the git endpoints in the GHA or Tekton pipelines due to the nature of the cloned repos (with detached HEAD).
This new change will perform schematics upgrade tests just like the regular terratest logic works.
```
/run pipeline
```
- Use a conventional commit message to set the release level. …
=> fix: schematics upgrade refactor to tar file only

common/general.go, common/general_test.go, testschematic/schematics.go, testschematic/tests.go
Small fix for schematics tests, that will now convert more composite input value types using a Json Marshal, so that their format when sent to schematics workspace is in proper json format instead of golang. The list of composite golang types that are converted are now:
- Array
- Slice
- Map (new)
- Struct (new)
- Interface (new)
```
/run pipeline
```
- Include information that …
=> fix: schematics convert inputs to json

common/random.go, testaddons/test_options.go, testhelper/test_options.go, testprojects/test_options.go, testschematic/test_options.go
control random hash length for prefix. Default length is 3 but can be controlled by passing an argument to UniqueId() function in common package.
```
/run pipeline
```
=> feat: control random hash length for prefix

cloudinfo/catalog.go
Cannot onboard offerings from branches like `renovate/ci-deps` without url encoding them first. This fixes the issue.
```
/run pipeline
```
=> fix: url encode offering branch name

cloudinfo/catalog.go, docs/projects/addons/troubleshooting.md, docs/projects/addons/validation-hooks.md, testaddons/tests.go, testaddons/tests_test.go
Some details where not getting populated in the dependency tree due to code to optimise the processing. This should fix it. 
Changed undeployed requirements to warning instead of error as it is an expected state. 
```
/run pipeline
```
- …
=> Fix dep bug

.secrets.baseline, docs/projects/addons/configuration.md, testaddons/tests.go
for issue - https://github.ibm.com/GoldenEye/issues/issues/16169
Overriding dependency inputs addons was not working because we were not making calls to update dependency configurations. 
```
/run pipeline
```
- Use the **Squash and …
=> Fix overriding dependency inputs addons
