terraform-ibm-modules/ibmcloud-terratest-wrapper

.github/workflows/main.yml, .releaserc
Add semantic release to this repository
**GIT issue:**
=> ci: add semantic release

.releaserc
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
**GIT issue:**
=> ci: change releaserc format

LICENCE
=> fix: add licence

.github/workflows/main.yml
If we want to sign releases we need to use the functional id's token for committing the releases 
=> Use Functional ID Token to Enable Release Signing 

.github/workflows/main.yml, .github/workflows/release.yml, .releaserc, .secrets.baseline, package.json
Add release workflow with signing
=> New Release Workflow

README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
=> fix: Add doc fix

.secrets.baseline, package-lock.json
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
=> fix: add lock file

.github/workflows/release.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
=> fix: checkout with token

testhelper/general.go
remove GoldenEye ref in general.go
=> docs: remove GoldenEye ref in general.go

testhelper/general.go, testhelper/general_test.go
When creating the cloudinfo package functionality for PowerSystems, forgot to create a new function in the testhelper package that wraps the new cloudinfo functions into something used from Terraform tests.
Added the appropriate wrapper function in the testhelper package that utilizes the new cloudinfo functions for determining PowerSystems region availability
=> fix: added testhelper.GetBestPowerSystemsRegion

.github/settings.yml, README.md
- adds name and description to the pipeline
- also syncs sections of main readme
=> ci: (settings) add name and desc

testhelper/tests.go
Added verbose change information, in JSON format, to any consistency check errors that occur for both regular and upgrade tests.
The JSON is formatted and human-readable, and is appended to the current error message for the resource that is reporting change. This will trigger for all changes caught (create/delete/update).
**Check the relevant boxes:**
- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).
=> fix: added verbose change detail for consistency check errors

testhelper/test_options.go, testhelper/tests.go
To perform apply operation on PR branch, code changes are done to include optional flag to perform upgrade test.
**Check the relevant boxes:**
- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).
=> feat: added optional upgrade for PR branch

testhelper/tests.go
issue #1847
**Check the relevant boxes:**
- [X ] New feature (nonbreaking change that adds functionality)
- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).
=> AddsApiDataIsSensitiveTrue

.secrets.baseline, testhelper/tests.go
Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.
**Check the relevant boxes:**
- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).
=> fix: only output diff on update

testhelper/tests.go
expose `TestSetup` and `TestTearDown` as public methods
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
=> feat: expose functions as public

common/general.go, common/general_test.go
Added function to load yaml into a map from a path
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
=> feat: add load from yaml

.github/workflows/ci.yml
=> Update pipeline version

.github/workflows/ci.yml
=> Update ci.yml pipeline

.secrets.baseline, testhelper/tests.go
=> revert to old test

.secrets.baseline, testhelper/tests.go
=> Teardown Only delete directory if it exists

testhelper/terraform.go
=> improve log message

common/general.go, common/general_test.go, sample/scripts/hello.sh, sample/terraform/sample4/main.tf, sample/terraform/sample4/variables.tf, sample/terraform/sample4/version.tf, testhelper/tests_test.go
=> Fix script permissions

.secrets.baseline, common/general.go, common/general_test.go, testhelper/tests.go
Add additional validation to prevent panics if the diff cannot be parsed
```
/run pipeline
```
=> add extra validation

.secrets.baseline, common/json_helpers.go, common/json_helpers_test.go, testhelper/tests.go
we were doing the diff after sanitising the json. This caused no diff to be seen if the only changes were seen in secure values.
- diff before sanitization happens
- add sha256 hash to the sanitized values to compare sensitive values
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the …
=> Fix diff order

.secrets.baseline, cloudinfo/containers.go, cloudinfo/containers_test.go, cloudinfo/mock_test.go, cloudinfo/service.go, cloudinfo/service_test.go, go.mod, go.sum
- add support to cloudinfosvc to get IKS configuration for connecting to a cluster
```
/run pipeline
```
=> add containers for getting iks config

.secrets.baseline, cloudinfo/mock_test.go, cloudinfo/resourcecontroller.go, cloudinfo/resourcecontroller_test.go, cloudinfo/resourcemanager.go, cloudinfo/resourcemanager_test.go, cloudinfo/service.go, testhelper/tests.go
=> add resource group print on failure

.secrets.baseline, common/general.go, common/general_test.go, testhelper/tests.go
Adding Helper function for string contains, Refactored some existing tests, updated the upgrade test directory copy to ignore additional files. 
```
/run pipeline
```
=> Add Helper function and refactor tests

cloudinfo/resourcecontroller.go, cloudinfo/resourcecontroller_test.go, testhelper/tests.go
Previously the destroy caused the test to end immediately, changing the destroy call and handling the error manually so we could print the resources left in the existing resource groups
```
/run pipeline
```
- Use the **Squash and merge** …
=> Print Rg failure

.secrets.baseline, testhelper/tests.go
Output the commit messages to help debug when things don't work as expected.
```
/run pipeline
```
=> add commit message output

testhelper/tests.go
Used sprintf instead of printf, this is to fix that
```
/run pipeline
```
=> print commit message output

.secrets.baseline, testhelper/tests.go
fixes bug where if a pr comes from a fork the commit messages were checked between the main/master of the fork and the pr. If the PR came from a fork on main/master there would be no commits listed. Now we add the upstream base repo, fetch the commits and check against the correct repo/braches
```
/run pipeline
```
- Include information that users need to know about the PR in …
=> Update skip check

README.md, testhelper/test_options.go
=> update docs for upgrade

README.md
Example to test the output value.
```
/run pipeline
```
=> docs: example to test output value

testhelper/test_options.go
Update default region to us-south
```
/run pipeline
```
=> Update default region to us-south

.secrets.baseline, cloudinfo/projects.go, cloudinfo/service.go, cloudinfo/structs.go, testprojects/test_options.go, testprojects/tests.go, testprojects/tests_test.go
Stack level input where not being correctly handled
```
/run pipeline
```
=> update stack input handling

cloudinfo/structs.go, testprojects/test_options.go, testprojects/tests.go
- modified stacks struct
- increased logging on projects test failure
```
/run pipeline
```
=> minor fixed

cloudinfo/projects.go, testprojects/tests.go
=> update log messages

testprojects/tests.go
=> enhance error message

.secrets.baseline, testprojects/tests.go
=> fix: ensure all stack members are listed in the stack order

.secrets.baseline, cloudinfo/catalog.go, cloudinfo/catalog_test.go, cloudinfo/service.go, common/general.go, testhelper/general_test.go, testprojects/general.go, testprojects/general_test.go, testprojects/testdata/stack_definition_valid.json, testprojects/tests.go
=> Various Enhancements

cloudinfo/projects.go
=> nil to __NULL__

.secrets.baseline, cloudinfo/projects.go, testprojects/tests.go
LastDeployed is contained in multiple places. I was looking in deployedConfigVersion when I should have been looking in deployedConfig...
```
/run pipeline
```
=> Projects get deploy fail reason

testprojects/tests.go
=> fix: fix bug, fail test on any deploy error

testprojects/tests.go
=> only keep the project on failure

.secrets.baseline, cloudinfo/projects.go
passing arrays directly from go was the problem, the SDK expects a string format
```
/run pipeline
```
=> fix: bug with stack arrays

testprojects/tests.go
Fix bug to fail undeploy if stack is in undeploy_failed state
```
/run pipeline
```
=> Fail if undeploy stack fails

testprojects/tests.go
Add an additional check before Undeploy, to ensure we do not trigger while still deploying.
```
/run pipeline
```
=> Add and additional check before Undeploy

testprojects/tests.go
This pull request includes changes to the `testprojects/tests.go` file, focusing on improving the `TriggerUnDeploy` and `TriggerUnDeployAndWait` functions. The main updates involve modifying the return types and enhancing error handling to provide more detailed feedback.
* Changed the return type of `TriggerUnDeploy` from `[]error` to `(bool, []error)` to indicate whether the undeploy operation was triggered successfully. (`testprojects/tests.go`)
* Updated error handling to return a boolean flag along with errors, providing more context on the operation's success. (`testprojects/tests.go`) [[1]](diffhunk://#diff-45408c12c9f14c53ae305004337820d4c20c9cdf884449a018dbbc7bc0a0f515L387-R400) [[2]](diffhunk://#diff-45408c12c9f14c53ae305004337820d4c20c9cdf884449a018dbbc7bc0a0f515L430-R450)
* …
=> handle failed edge cases

README.md, testprojects/test_options.go
=> add documentation for projects test

common/logger.go, common/logger_test.go, testprojects/test_options.go, testprojects/tests.go, testprojects/tests_test.go
Custom logger added including the ability to colorize logs for easier consumption. 
Works on local machine and in GHA, not tested in Tekton
```
/run pipeline
```
=> Add custom Logger

cloudinfo/projects.go, cloudinfo/projects_mock_test.go, cloudinfo/projects_test.go, cloudinfo/structs.go, cloudinfo/testdata/ibm_catalog_with_config_overrides.json, cloudinfo/testdata/stack_definition_stack_inputs_extended.json
=> update bug fix for catalog types and add tests

README.md
=> docs: fixed the release badge

.secrets.baseline, common/git.go, common/git_test.go
=> feat: Add function to check if there are local git changes not yet pushed

testschematic/tests.go
create TestTearDown public method in testschematics
```
/run pipeline
```
=> create TestTearDown public method in testschematics

.secrets.baseline, cloudinfo/catalog.go, cloudinfo/catalog_mock_test.go, cloudinfo/catalog_test.go, cloudinfo/service.go, testaddons/tests.go
for issue - https://github.ibm.com/orgs/GoldenEye/projects/3?pane=issue&itemId=1397668&issue=GoldenEye%7Cissues%7C13334
```
/run pipeline
```
=> added function GetOffering

.secrets.baseline, cloudinfo/catalog.go, cloudinfo/catalog_test.go, cloudinfo/projects_types.go, cloudinfo/service.go, testaddons/tests.go
for issue - https://github.ibm.com/GoldenEye/issues/issues/13334
```
/run pipeline
```
=> project config input validation

docs/projects/addons/testing-process.md, docs/projects/addons/validation-hooks.md, testaddons/tests.go
=> fix validation skip

cloudinfo/catalog.go, testaddons/print_utils.go, testaddons/tests.go
=> fix: remove optimisation tha introduced bug. enhance addon dependency visualization with comprehensive tree structure and circular reference detection

cloudinfo/catalog_types.go
=> fix: update CatalogJson and CatalogInput structs to use omitempty and interface{} for options

cloudinfo/catalog.go, cloudinfo/catalog_test.go, docs/projects/addons/configuration.md, docs/projects/addons/dependency-permutation-testing.md, docs/projects/addons/overview.md, docs/projects/addons/parallel-testing.md, testaddons/dependency_graph.go, testaddons/permutation_test.go, testaddons/print_utils.go, testaddons/test_options.go, testaddons/tests.go, testaddons/tests_test.go
- Fixes the dependecy tre resolution
- added the ability to skip ceritan permutaion test combinations
- simplified some code paths
```
/run pipeline
```
=> feat: fix dep tree resolution

.secrets.baseline, cloudinfo/catalog.go, common/retry.go, docs/projects/addons/configuration.md, testaddons/offering_utils.go, testaddons/setup_teardown.go, testaddons/test_options.go, testaddons/types.go
=> Expose retry variables and handle retry already exits

.secrets.baseline, cloudinfo/catalog.go, cloudinfo/catalog_mock.go, cloudinfo/projects.go, cloudinfo/ref_resolver.go, cloudinfo/service.go, docs/cache-optimization.md, testaddons/offering_utils.go, testaddons/setup_teardown.go, testaddons/test_options.go, testaddons/tests.go, testhelper/test_options.go, testhelper/tests.go, testprojects/test_options.go, testprojects/tests.go
=> feat: add caching

common/retry.go, common/retry_test.go
=> fix: update retry configurations for catalog and project operations
